### ISSUE TITLE
5 new improvements

### ISSUE THREAD

**Issue by gutermanyair** [UBC-MDS/your_happy_place#25]

**Comment by Radascript** [comment]
The changes I made to the app:
1) Based on Affrin's peer review suggestion: we made the time x-axis nicer and more meaningful, and they now have month names for scalehttps://github.com/UBC-MDS/your_happy_place/commit/a8c9a5277234450d0b5eb30638a4e8945ce0440d
2) We implemented Affrin's suggestions of putting different charts on different tabs. I sorted them into "Social charts" and "Climate charts." That was a great idea - any future charts can be classified, too.https://github.com/UBC-MDS/your_happy_place/commit/a8c9a5277234450d0b5eb30638a4e8945ce0440d

3) We added titles and subtitles to sections (now tabs)https://github.com/UBC-MDS/your_happy_place/commit/2e0039e89b74f4210c02694b420703ba191c69bf

4) We implemented Affrin's suggestion that the bar plots would look better horizontal rather than vertical.https://github.com/UBC-MDS/your_happy_place/commit/2e0039e89b74f4210c02694b420703ba191c69bf

5) Improved padding of everything so the app looks less jammed, and added little thin borders.https://github.com/UBC-MDS/your_happy_place/commit/058d47b1aeb64ac106272e0225e6cfff573e54e9

6) Added "for DSCI532" and "by" sections below the title, with links to our team's git profiles.https://github.com/UBC-MDS/your_happy_place/commit/622f4e21f745fe96091a4d39d270eadc4fe67eaf
